services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_DATABASE: financial_system_db
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  frontend:
    image: node:22-alpine
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  sqlserver_data:
