services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: financial_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong!Passw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: node:22-alpine
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - ./frontend/app:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  postgres_data:
